ws createinstaller: improve output of initialize
Suppress overly verbose output of some invoked commands

diff --git a/src/ws-createinstaller b/src/ws-createinstaller
--- a/src/ws-createinstaller
+++ b/src/ws-createinstaller
@@ -49,6 +49,9 @@ __ros_version=$(get_rosversion) || exit 1
 echo "Using ROS $__ros_version"
 
 
+# Would you like some bash generated by bash that has been generated by this?
+# Sure there is a clearer way to do it. But this way this initialization script
+# is self-contained. 
 SCRIPT_PATH=$metapack_dir/initialize
 echo "Creating $SCRIPT_PATH"
 echo \
@@ -91,71 +94,75 @@ if [ "$updirname" != "$name" ];then
   exit 1
 fi
 
+#################################################
+# Helper functions
+green=$(echo -e "\033[0;32m")
+red=$(echo -e "\033[0;31m")
+grey=$(echo -e "\033[0;90m")
+bwhite=$(echo -e "\033[1;37m")
+no_color=$(echo -e "\033[0;m")
+
+__draw_line(){
+  char=$1
+  text=" $2 "
+  text_color=$3
+  if [ -z "$text_color" ]; then text_color=$no_color; fi
+  terminal_width=$(tput cols) 
+  let w2=$((($terminal_width-${#text})/2))
+  line=$(for (( c=0; c<$w2; c++)); do echo -n $char; done)
+  echo -e "\n$grey$line$text_color$text$grey$line$no_color"
+}
+
+__exec_longrunning(){
+  echo -n "$*$grey "
+  $* | xargs -I {} echo -n .
+  echo $no_color
+}
+
 # Some error handling
 success=""
 __unsuccessfull_exit(){
   if [ -z "$success" ]; then
-    echo "
-    ========================================
-    Initialization script did not go
-    all the way!  Check the errors
-    ========================================
-    "
+    __draw_line ^ "Did not finish, check any errors" $red
   fi
 }
 trap ''__unsuccessfull_exit'' EXIT
 
 
+#####################################################
+__draw_line = "Workspace initialization script for $name"
+
 ROSWS_INSTALL_DIR=$updir
 ROSINSTALL_FILE=$thisdir/workspace.rosinstall
 
 initializePrerequisites(){
-  echo "
-  ========================================
-  Setting up tools required to initialize workspace
-  ========================================
-
-  "
-  sudo apt-get install -y --force-yes python-rosinstall python-rosdep
-  sudo rosdep init && rosdep update
+  __draw_line + "Setting up tools required to initialize the workspace"
+  __exec_longrunning sudo apt-get install -y --force-yes python-rosinstall python-rosdep
+  __exec_longrunning sudo rosdep init  || echo "Ignoring rosdep init error"
+  __exec_longrunning rosdep update 
 }
 
 initializeWorkspace()
 {
-  echo "
-  ========================================
-  Initializing workspace: $ROSINSTALL_FILE
-  ========================================
-
-  "
+  __draw_line + "Initializing workspace: $ROSINSTALL_FILE"
   # Overlay over current ROS environment
-  rosinstall $ROSWS_INSTALL_DIR $(dirname $(dirname $ROS_ROOT)) $ROSINSTALL_FILE
+  __exec_longrunning rosinstall $ROSWS_INSTALL_DIR $(dirname $(dirname $ROS_ROOT)) $ROSINSTALL_FILE
 
   source $ROSWS_INSTALL_DIR/setup.bash
 }
 
 buildWorkspace(){
-  echo "
-  ========================================
-  Building workspace
-  ========================================
-
-  "
-  rosmake -a 
+  __draw_line + "Building the workspace"
+  __exec_longrunning rosmake -a 
 }
 
 initializeEclipseProjects(){
-  echo "
-  ========================================
-  Building workspace eclipse projects
-  ========================================
-
-  "
-  rosmake -a --target=eclipse-project
+  __draw_line + "Building workspace eclipse projects"
+  __exec_longrunning rosmake -a --target=eclipse-project 
 }
 
 createEnvLoader(){
-  echo "(Over)writing $ENV_FILE"
+  __draw_line + "(Over)writing $ENV_FILE"
 echo '"'"'#!/bin/sh
 # ROS Environment loader for roslaunch.
 # This file may be overwritten next time *-workspace/initialize is run.
@@ -185,7 +192,7 @@ fi'"'"' > $ENV_FILE
 
 
 createWorkspaceRC(){
-  echo "(Over)writing $WSRC_PATH"
+  __draw_line + "(Over)writing $WSRC_PATH"
 echo "# Current ROS workspace setting.
 # This may be overwritten next time the *-workspace/initialize script is run.
 # Feel free to edit this to manually switch the workspace.
@@ -199,30 +206,28 @@ if [ "'"'"'$-'"'"'" = "'"'"'*i*'"'"'" ]; then return 0; fi
 source "'"'"'$ROS_WORKSPACE'"'"'"/setup.bash
 
 # Below is the place to put non-essential commands that 
-# would be run each time a new interactive shell is opened.
-# System should not depend on these to be run.
+# would be run each time the script is sourced from interactive shell.
+# There are no guarantees that it would be sourced, so 
+# your system should not depend on these to work properly.
 # An example is to print out the workspace state, help messages, etc.
 " > $WSRC_PATH
 }
 
 successMessage(){
+  __draw_line = Done $green
   echo "
-  ========================================
-  Done. To start using the workspace: 
-
+  ## To start using the workspace: 
   source $ROSWS_INSTALL_DIR/setup.bash
-  or
-  source $WSRC_PATH # May contain additional ws customization
-
-  Alternatively, add either to your ~/.bashrc
-  ========================================
+  ## or
+  source $WSRC_PATH 
+  ## Alternatively, add either to your ~/.bashrc
   "
 }
 
 initializePrerequisites
 initializeWorkspace
 buildWorkspace
-initializeEclipseProjects
+#initializeEclipseProjects
 createEnvLoader
 createWorkspaceRC
 successMessage
